### ISSUE TITLE
How to Input URL

### ISSUE THREAD

**Issue by dbrakman** [philbot9/youtube-comment-scraper#1]
I'm attempting to run this project on my local machine, but I can't figure out how to supply the Youtube URL from which I want to scrape comments.

**Comment by philbot9** [comment]
Hi there,
The YouTube URL is entered in the web interface. If you're just looking to scrape comments from a video I would recommend using the hosted version at http://ytcomments.klostermann.ca.

If you'd like to work with the code, you can deploy it on your local machine with Docker (See [README](https://github.com/philbot9/youtube-comment-scraper/blob/master/README.md)), or simply run `npm start` and open http://localhost:8080/ in your browser.

Please let me know if you run into any issues.

**Comment by dbrakman** [comment]
@philbot9 Thanks for getting back to me so quickly! I had used the hosted version but didn't see results displayed after the progress bar finished.

I haven't used Docker before and didn't think to open http://localhost:49161 in my browser. That exposed the interface I was looking for. Thanks!
