### ISSUE TITLE
cannot scrape comments from USA's videos

### ISSUE THREAD

**Issue by shizhediao** [philbot9/youtube-comment-scraper#12]
Hi, thanks for your excellent work!
I tried the website to scrape some videos from USA. Unfortunately, I encountered a problem, which says, 
"Video Error
This video is not available in the location of the server. Please ensure the video is available in Canada.

Having problems? Report an issue."

Could you help me to solve this, Thanks very much!

eg link: https://www.youtube.com/user/SaturdayNightLive/videos

**Comment by philbot9** [comment]
Hi,

As stated in the error message videos that are not available in Canada cannot be scraped using the hosted service (http://ytcomments.klostermann.ca/). The server running the scraper is located in Canada and some YouTube videos and their comments are not available with a Canadian IP.

You can either ask the uploader to make the video available in Canada, or run the scraper locally using https://github.com/philbot9/youtube-comment-scraper-cli for example.
