### ISSUE TITLE
Broken link to Scraper Comments ?

### ISSUE THREAD

**Issue by IlanaDub** [philbot9/youtube-comment-scraper#14]
Hi 
I am receiving - 502 Bad Gateway.

**Comment by philbot9** [comment]
Yes, the server got corrupted and I had to deactivate the scraper. I will set up a replacement server when I have the time.

**Comment by philbot9** [comment]
New server is up and running.

**Comment by IlanaDub** [comment]
Apologies for bothering you again, however it seems that the web link is still broken.  I am receiving that Safari cannot connect to the server. This website is a great deal of help for my research. Thank you for your support and effort!
<img width="591" alt="Screen Shot 2019-04-08 at 16 56 11" src="https://user-images.githubusercontent.com/48861151/55729916-b5144000-5a1f-11e9-9281-f3658751213a.png">

**Comment by IlanaDub** [comment]
Thank you. Now its working!

Best
