### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by pococito** [philbot9/youtube-comment-scraper#15]
Hi Philip,
Great job with this scraper!
It works anonymously with pages. How can it be used or where should I modify the code to be able to login with youtube user credentials including account choice?
Comments visible when accessing the page anonymously differ from what is seen when logged in. I'd like to be able to compare the two.
Thanks

**Comment by philbot9** [comment]
Hi Paweł,

Thanks, I do see the use case, but I think it goes beyond the scope of this scraper. This one scrapes the comments from the public HTML of a YouTube video. While it might be technically possible to make it work with an authenticated user, I think in your case you might be better off using the official YouTube API. It'd be less work and it's documented :wink:
https://developers.google.com/youtube/v3/docs/comments/list

Good Luck!

**Comment by pococito** [comment]
Thanks for the link and hint, Philip. Sounds reasonable :)

**Comment by spiralofhope** [comment]
@pococito 

If you do complete this work, please drop by and let me know.

I am interested in the revelation of any "curated comments" when logged in or not.

(I have already tested that shadow banning exists, and not by a channel author's actions.)

**Comment by pococito** [comment]
Yes, that's that - shadow banning. All comments are visible in the posting
account, but some comments are not visible to outside users. I'm not aware
of any content curating, which would change it. I will most probably just
analyze a couple pages manually and gather stats. Probably won't have time
to write scripts for that unfortunately...
