### ISSUE TITLE
multithreaded scraping

### ISSUE THREAD

**Issue by TAbdiukov** [philbot9/youtube-comment-scraper#25]
Hey,

Given the performance scraper has, it appears the scraper only uses 1 thread to scrape. The performance can be improved by adding multi-threading support

(enhancement suggestion)

**Comment by philbot9** [comment]
Thanks for your suggestion. Unfortunately that’s not the case.

1) Node.js is single-threaded
2) The comments are paginated. Each page responds with a page token for the next page, and as far as I know it’s not possible to get the phage token for subsequent pages.

Cheers,
Philip

**Comment by philbot9** [comment]
Thanks for your suggestion. Unfortunately that’s not the case.

1) Node.js is single-threaded
2) The comments are paginated. Each page responds with a page token for the next page, and as far as I know it’s not possible to get the page token for subsequent pages.

Cheers,
Philip
