### ISSUE TITLE
Limited use ?

### ISSUE THREAD

**Issue by tissatussa** [philbot9/youtube-comment-scraper#26]
Thank you for this script. It's exactly what i was looking for, it even saves replies! It seems you built this app 3 years ago and it still works! (i know that YouTube changes its code / function from time to time and then some apps / addons stop functioning).

I found your script by an answer on Quora :

How can I export YouTube comments into a spreadsheet? : https://www.quora.com/How-can-I-export-YouTube-comments-into-a-spreadsheet

The first answer is from Rajan Elangovan, on Mar 14, 2019.  He states :
_Is There Any App To Download Youtube Comments?
There are so many tools in the market like youtube comment scraper, [..] but those are just doing the web scraping and after few days of use, it’ll be banned by Youtube search engine since it is against Youtube terms. [..]_

Is this true ?
(I use your web-based version at http://ytcomments.klostermann.ca )

I have some experience in webdevelopment and coding, but I'm not yet able to install your app by using the GitHub code, because i'm not familiar with Node.js .. is there another way install youtube comment scraper ?

**Comment by philbot9** [comment]
Hi there,

You can use the command line version of the scraper: https://github.com/philbot9/youtube-comment-scraper-cli

I don't know whether or not that person's claim is true. If you were to use YouTube's official API to pull down a bunch of comments you would eventually run out of the allowable usage quota. This project does not use the API and scrapes the comment HTML directly. I doubt there is much YouTube can do to stop that. Sounds to me like that person is trying to sell you something... 

Note that the data is limited to what's available on the YouTube website. Notably, the `timestamp` is only an approximation based on the relative time (i.e. 1 hour ago, 1 week ago, 1 year ago, ...).

Also, I haven't touched this project in a while and there are some known issues (see https://github.com/philbot9/youtube-comments-task/issues).

**Comment by tissatussa** [comment]
Thanks for this quick and complete answer.  I managed to install nodejs and npm and i ran the CLI .. it works !  Great job !
