### ISSUE TITLE
It shows video Error in every url

### ISSUE THREAD

**Issue by Essie0715** [philbot9/youtube-comment-scraper#27]
It works well before
but today every url shows video error

**Comment by Essie0715** [comment]
It can not use again

**Comment by philbot9** [comment]
@Essie0715 Sorry, I don't really know what you mean. Can you please provide more detail what you're trying to do and where?

If you're referring to http://ytcomments.klostermann.ca/ being down, please follow this topic: https://github.com/philbot9/youtube-comment-scraper/issues/28#issuecomment-543311549

**Comment by rocawhey** [comment]
I'm afraid this issue has returned. Getting this error for every video I've tried so far.

Video Error

The comments on this video cannot be scraped.

Having problems? Report an issue.

**Comment by philbot9** [comment]
Please refer to this issue: https://github.com/philbot9/youtube-comment-scraper/issues/28
