### ISSUE TITLE
Locally-activated youtube-comment-scraper

### ISSUE THREAD

**Issue by spiralofhope** [philbot9/youtube-comment-scraper#32]
Visiting `http://localhost:49161/`, the installation works, but it is disabled just like `http://ytcomments.klostermann.ca/`

Since my IP is (probably) not banned I'd like to use it anyway.

----

See also issue #28 (YouTube comment scraper deactivated)

**Comment by philbot9** [comment]
Sure, you just need to undo this commit: https://github.com/philbot9/youtube-comment-scraper/commit/1342325d81d316e4bd6ea593dcadcf84256604d7#diff-bb503f3d9047bcd4a5730559f1e16560

In the file `/routes/index.js` remove  line 5 and un-comment line 4.

**Comment by spiralofhope** [comment]
This did the trick, thanks!

I'm not sure if this should be closed or remain open for others to easily find.

**Comment by coolankit** [comment]
Hi Philip /Spiralofhope,

Is it stil worrking in local system.  I'm trying hard to ge tthis but not working in mine with error message : **_API response does not contain a "content_html" field_**

**Comment by spiralofhope** [comment]
I'm now using https://github.com/philbot9/youtube-comment-scraper-cli so I can't help directly.

I have seen this issue with the cli version, and [I have my own ticket here](https://github.com/philbot9/youtube-comment-scraper-cli/issues/46), which you can subscribe to for any future notifications:
