### ISSUE TITLE
Scraper FAILS if the first character of Video ID is '-'

### ISSUE THREAD

**Issue by ae8-little** [philbot9/youtube-comment-scraper#38]
"https://youtube.com/watch?v=-HCTNmBXPKU&local=true"

youtube-comment-scraper -V
1.0.1

In CMD:

youtube-comment-scraper -HCTNmBXPKU
error: unknown option `-H'

youtube-comment-scraper "-HCTNmBXPKU"
error: unknown option `-H'

youtube-comment-scraper '-HCTNmBXPKU'
✕ This video does not exist.

CMD Sequence of two commands:

set _k=-HCTNmBXPKU && echo %_k% && youtube-comment-scraper %_k%
%_k%
✕ This video does not exist.

set _k=-HCTNmBXPKU && echo %_k% && youtube-comment-scraper %_k%
-HCTNmBXPKU
error: unknown option `-H'

In Cygwin64 Terminal:

$ youtube-comment-scraper -HCTNmBXPKU
error: unknown option `-H'

$ youtube-comment-scraper "-HCTNmBXPKU"
error: unknown option `-H'

$ youtube-comment-scraper '-HCTNmBXPKU'
error: unknown option `-H'

$ _a="-HCTNmBXPKU"
$ youtube-comment-scraper $_a
error: unknown option `-H'

**Comment by philbot9** [comment]
https://github.com/philbot9/youtube-comment-scraper-cli/issues/19#issuecomment-531235625
