### ISSUE TITLE
can't scrape comments from videos with only 1 comment

### ISSUE THREAD

**Issue by fin-atem** [philbot9/youtube-comment-scraper#9]
so i notice that on every youtube video i try to scrape the comments on when there is only one comment, youtube-comment-scraper thinks there aren't any comments.

Try with this video for example: https://www.youtube.com/watch?v=0eOD_nylWG8

as of Sep 20 07:40 UTC, it has only one comment.

**Comment by philbot9** [comment]
@fin-atem Thanks for this. The issue was fixed a couple weeks ago. I forgot this Issue was here.
